#===================================================
#               然就的PokeGuild 插件配置文件
#
#                   主要翻译注释:然就
#===================================================

#插件前缀
Prefix: "&e[&c PokeGuild&e ]&l: "

#点券功能是否开启
PlayerPoints: true

#金币功能是否开启
Vault: true

#公会货币是否开启
Guild_Vault: False


#公会积分设置(升级经验)
Guild_integral:

  #一周内积分是否有上线
  integral_STOP: true

  #积分上线(一周内【需要上方为true才会生效】)
  integral_MAX: 300

  #升级时积分是否为BOSS积分
  integral_PokeBoss: true

  #BOSS积分需要(需要上方为true)
  integral_PokeBoss_Number: 3

#注册公会id
Guild_List:
  - "然就的之上公会"

#公会信息
Guild_Info:

  #识别ID
  然就的之上公会:

    #积分
    integral: 0

    #公会币
    guild_money: 0

    #公会超级boss攻击数
    Super-Boss:
      #等级:数量
      1: 0

    #描述
    describe: ""

    #等级
    level: 0

    #最大人数
    Max_player: 10

    #玩家列表
    Player:
      - "ranjiu"

    #职务分配
    job:

      #会长
      Master: "ranjiu"

      #副会长
      Vice-Master: null

#公会升级设置
Guild_level:

  #注册表
  register:
    - 1

  #等级设置
  level:

    #升到1级需要
    1:
      #积分
      integral: 500
      #超级boss设定
      Super-Boss:

        #等级:个数
        1: 3
      #金币
      money: 3000

#公会boss设定
Guild-Super-Boss:

  #注册表
  register:
    - 1

  #1级的boss设定
  1:
    #等级
    level: 150
    #血量
    health: 5000
    #宝可梦 (输入宝可梦英文名)
    name: ""
    #显示名
    nickname: "&c1级公会超级boss"
      # 对战精灵的 四个技能 - 使用技能的英文名 用你的宝可梦编辑器看
      moveset1: "memento"
      moveset2: "memento"
      moveset3: "memento"
      moveset4: "memento"
      # 此宝可梦可用特性-在宝可梦编辑器中查看-输入特性的英文名
      Ability: "神奇守护"
